
---
apiVersion: admissionregistration.k8s.io/v1
kind: MutatingWebhookConfiguration
metadata:
  creationTimestamp: null
  name: mutating-webhook-configuration
webhooks:
- admissionReviewVersions:
  - v1
  - v1beta1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /mutate-l6p-io-v1-kuninstallation
  failurePolicy: Fail
  name: mkuninstallation.kb.io
  rules:
  - apiGroups:
    - l6p.io
    apiVersions:
    - v1
    operations:
    - CREATE
    - UPDATE
    resources:
    - kuninstallations
  sideEffects: None

---
apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingWebhookConfiguration
metadata:
  creationTimestamp: null
  name: validating-webhook-configuration
webhooks:
- admissionReviewVersions:
  - v1
  - v1beta1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /validate-l6p-io-v1-kuninstallation
  failurePolicy: Fail
  name: vkuninstallation.kb.io
  rules:
  - apiGroups:
    - l6p.io
    apiVersions:
    - v1
    operations:
    - CREATE
    - UPDATE
    resources:
    - kuninstallations
  sideEffects: None
