# permissions for end users to view kuninstallations.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: kuninstallation-viewer-role
rules:
  - apiGroups:
      - l6p.io
    resources:
      - kuninstallations
    verbs:
      - get
      - list
      - watch
  - apiGroups:
      - l6p.io
    resources:
      - kuninstallations/status
    verbs:
      - get
