apiVersion: l6p.io/v1
kind: KunInstallation
metadata:
  name: sample
spec:
  registry:
    hub: localhost:32000
    auth:
      - authority: registry.l6p.io
        username: username
        password: password
  mongodb:
    addr: "mongodb.default.svc.cluster.local:27017"
    user: "root"
    pass: "rootpassword"
  server:
    replicas: 1
    port: 80
    resources:
      requests:
        cpu: 0.1
        memory: 512Mi
    ingress:
      enabled: true
      host: kun.l6p.io
      path: /api/v1
  ui:
    enabled: true
    replicas: 1
    port: 80
    resources:
      requests:
        cpu: 0.1
        memory: 512Mi
    ingress:
      enabled: true
      host: kun.l6p.io
      path: /
