apiVersion: l6p.io/v1
kind: KunInstallation
metadata:
  name: sample
spec:
  hub: localhost:32000
  clickhouse:
    addr: "tcp://clickhouse-kun.default:9000?username=user&password=123456&debug=true"
  server:
    replicas: 1
    port: 80
    resources:
      requests:
        cpu: 0.1
        memory: 512Mi
    ingress:
      enabled: true
      host: kun.l6p.io
      path: /api/v1
  ui:
    enabled: true
    replicas: 1
    port: 80
    resources:
      requests:
        cpu: 0.1
        memory: 512Mi
    ingress:
      enabled: true
      host: kun.l6p.io
      path: /
